package glean

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// (Note: This is a prototype - in production this would be generated by glean_parser)

// Pub/Sub-based implementation of Glean events logger for high-throughput server-side telemetry.
// This implementation publishes events directly to Google Cloud Pub/Sub instead of stdout,
// bypassing Cloud Logging infrastructure for improved reliability.
//
// Key features:
// - Asynchronous batched publishing
// - Flow control to prevent memory exhaustion
// - Graceful shutdown with message flushing

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"runtime"
	"sync"
	"sync/atomic"
	"time"

	"cloud.google.com/go/pubsub"
	"github.com/google/uuid"
)

// exported type for public method parameters
type RequestInfo struct {
	UserAgent string
	IpAddress string
}

// default empty values will be omitted in json from ping struct definition
var defaultRequestInfo = RequestInfo{
	UserAgent: "",
	IpAddress: "",
}

// structs to construct the glean ping
type clientInfo struct {
	TelemetrySDKBuild string `json:"telemetry_sdk_build"`
	FirstRunDate      string `json:"first_run_date"`
	OS                string `json:"os"`
	OSVersion         string `json:"os_version"`
	Architecture      string `json:"architecture"`
	AppBuild          string `json:"app_build"`
	AppDisplayVersion string `json:"app_display_version"`
	AppChannel        string `json:"app_channel"`
}

type pingInfo struct {
	Seq       int    `json:"seq"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type ping struct {
	DocumentNamespace string `json:"document_namespace"`
	DocumentType      string `json:"document_type"`
	DocumentVersion   string `json:"document_version"`
	DocumentID        string `json:"document_id"`
	UserAgent         string `json:"user_agent,omitempty"`
	IpAddress         string `json:"ip_address,omitempty"`
	Payload           string `json:"payload"`
}

type metrics map[string]map[string]interface{}

type pingPayload struct {
	ClientInfo clientInfo   `json:"client_info"`
	PingInfo   pingInfo     `json:"ping_info"`
	Metrics    metrics      `json:"metrics"`
	Events     []gleanEvent `json:"events"`
}

type gleanEvent struct {
	Category  string            `json:"category"`
	Name      string            `json:"name"`
	Timestamp int64             `json:"timestamp"`
	Extra     map[string]string `json:"extra"`
}

// Cloud Logging envelope structure for ParseLogEntry decoder compatibility
// This matches the format expected by gcp-ingestion/ingestion-beam ParseLogEntry.java
// TODO: we should simplify this and create a dedicated transform in the Decoder
type cloudLoggingEnvelope struct {
	JsonPayload      jsonPayloadWrapper `json:"jsonPayload"`
	ReceiveTimestamp string             `json:"receiveTimestamp"`
}

type jsonPayloadWrapper struct {
	Fields ping `json:"Fields"`
}

// createClientInfo constructs client info metadata (same as stdout version)
func (g *GleanEventsPublisher) createClientInfo() clientInfo {
	return clientInfo{
		TelemetrySDKBuild: "glean_parser v15.0.2.dev17+g81fec69a (pubsub)",
		FirstRunDate:      "Unknown",
		OS:                "Unknown",
		OSVersion:         "Unknown",
		Architecture:      "Unknown",
		AppBuild:          "Unknown",
		AppDisplayVersion: g.AppDisplayVersion,
		AppChannel:        g.AppChannel,
	}
}

func createPingInfo() pingInfo {
	var now = time.Now().UTC().Format("2006-01-02T15:04:05.000Z")
	return pingInfo{
		Seq:       0,
		StartTime: now,
		EndTime:   now,
	}
}

func (g *GleanEventsPublisher) createPing(documentType string, config RequestInfo, payload pingPayload) ping {
	payloadJSON, err := json.Marshal(payload)
	if err != nil {
		panic("Unable to marshal payload to json")
	}
	documentID := uuid.New()
	return ping{
		DocumentNamespace: g.AppID,
		DocumentType:      documentType,
		DocumentVersion:   "1",
		DocumentID:        documentID.String(),
		UserAgent:         config.UserAgent,
		IpAddress:         config.IpAddress,
		Payload:           string(payloadJSON),
	}
}

func newGleanEvent(category, name string, extra map[string]string) gleanEvent {
	return gleanEvent{
		Category:  category,
		Name:      name,
		Timestamp: time.Now().UnixMilli(),
		Extra:     extra,
	}
}

type BackendObjectUpdateEvent struct {
	ObjectType  string // A simple name to describe the object whose state changed. For example, `api_request`.
	ObjectState string // A JSON representation of the latest state of the object.
	Linking     bool   // Indicates the initial linking of the Mozilla account and the third-party account.
}

func (e BackendObjectUpdateEvent) gleanEvent() gleanEvent {
	return newGleanEvent(
		"backend",
		"object_update",
		map[string]string{
			"object_type":  e.ObjectType,
			"object_state": e.ObjectState,
			"linking":      fmt.Sprintf("%t", e.Linking),
		},
	)
}

// EventsPingEvent is the interface for events that can be recorded in an events ping
type EventsPingEvent interface {
	isEventsPingEvent()
	gleanEvent() gleanEvent
}

func (e BackendObjectUpdateEvent) isEventsPingEvent() {}

// EventsPing contains parameters for recording an events ping
type EventsPing struct {
	IdentifiersFxaAccountId string          // The user's FxA account ID, if available.
	Event                   EventsPingEvent // valid event for this ping
}

// ============================================================================
// Pub/Sub Publisher Implementation
// ============================================================================

// GleanEventsPublisher publishes Glean events directly to Pub/Sub
type GleanEventsPublisher struct {
	AppID             string // Application ID to identify application per Glean standards
	AppDisplayVersion string // Version of application emitting the event
	AppChannel        string // Channel to differentiate logs from prod/beta/staging/devel

	topic          *pubsub.Topic
	ctx            context.Context
	publishedCount atomic.Int64
	errorCount     atomic.Int64
	pendingResults chan *pubsub.PublishResult
	wg             sync.WaitGroup
	once           sync.Once
}

// publishing statistics
type Stats struct {
	Published int64
	Errors    int64
}

// NewGleanEventsPublisher creates a new Pub/Sub-based Glean events publisher
// Authentication uses Application Default Credentials (ADC) - typically GKE Workload Identity
func NewGleanEventsPublisher(ctx context.Context, projectID, topicID, appID, appDisplayVersion, appChannel string) (*GleanEventsPublisher, error) {
	// Create Pub/Sub client using Application Default Credentials
	client, err := pubsub.NewClient(ctx, projectID)
	if err != nil {
		return nil, fmt.Errorf("failed to create pubsub client: %w", err)
	}

	topic := client.Topic(topicID)

	// Configure publish settings following Pub/Sub best practices for high throughput
	// https://cloud.google.com/pubsub/docs/publish-best-practices
	topic.PublishSettings = pubsub.PublishSettings{
		// Batching configuration - optimized for 40k msgs/s throughput
		CountThreshold: 1000,                   // Batch up to 1000 messages per publish
		ByteThreshold:  10e6,                   // 10 MB max batch size (Pub/Sub limit is 10MB)
		DelayThreshold: 100 * time.Millisecond, // Max 100ms batching delay for throughput
		Timeout:        60 * time.Second,       // Long timeout for high-throughput scenarios
		NumGoroutines:  runtime.NumCPU() * 2,   // Parallel publisher goroutines

		// Flow control prevents memory exhaustion when producing faster than publishing
		FlowControlSettings: pubsub.FlowControlSettings{
			MaxOutstandingMessages: 10000,                   // Buffer up to 10k messages
			MaxOutstandingBytes:    100e6,                   // 100 MB memory limit
			LimitExceededBehavior:  pubsub.FlowControlBlock, // Block Publish() calls when limit exceeded (backpressure)
		},
	}

	publisher := &GleanEventsPublisher{
		AppID:             appID,
		AppDisplayVersion: appDisplayVersion,
		AppChannel:        appChannel,
		topic:             topic,
		ctx:               ctx,
		pendingResults:    make(chan *pubsub.PublishResult, 10000), // Buffer for pending results
	}

	// Start background goroutine to process publish results asynchronously
	publisher.wg.Add(1)
	go publisher.processResults()

	return publisher, nil
}

// processResults runs in background to handle publish results asynchronously
func (g *GleanEventsPublisher) processResults() {
	defer g.wg.Done()

	for result := range g.pendingResults {
		// Get() blocks until the publish completes or fails
		_, err := result.Get(g.ctx)
		if err != nil {
			g.errorCount.Add(1)
			// Log error but don't block on I/O
			log.Printf("Pub/Sub publish error: %v", err)
		} else {
			g.publishedCount.Add(1)
		}
	}
}

// RecordEventsPing records and publishes an events ping to Pub/Sub
// This method is non-blocking and returns immediately after queuing the message
func (g *GleanEventsPublisher) RecordEventsPing(
	requestInfo RequestInfo,
	params EventsPing,
) error {
	var metrics = metrics{
		"string": {
			"identifiers.fxa_account_id": params.IdentifiersFxaAccountId,
		},
	}

	events := []gleanEvent{}
	if params.Event != nil {
		events = append(events, params.Event.gleanEvent())
	}

	return g.publish("events", requestInfo, metrics, events)
}

// RecordEventsPingWithoutUserInfo records and publishes an events ping without user request info
func (g *GleanEventsPublisher) RecordEventsPingWithoutUserInfo(
	params EventsPing,
) error {
	return g.RecordEventsPing(defaultRequestInfo, params)
}

// construct the Glean envelope and publish to Pub/Sub asynchronously
func (g *GleanEventsPublisher) publish(
	documentType string,
	requestInfo RequestInfo,
	metrics metrics,
	events []gleanEvent,
) error {
	var telemetryPayload = pingPayload{
		ClientInfo: g.createClientInfo(),
		PingInfo:   createPingInfo(),
		Metrics:    metrics,
		Events:     events,
	}

	var ping = g.createPing(documentType, requestInfo, telemetryPayload)

	// Wrap in Cloud Logging envelope for ParseLogEntry decoder compatibility
	// This matches the format produced by GCP Cloud Logging sink, allowing the same decoder
	// to process both Cloud Logging-sourced and direct Pub/Sub messages
	var envelope = cloudLoggingEnvelope{
		JsonPayload: jsonPayloadWrapper{
			Fields: ping,
		},
		ReceiveTimestamp: time.Now().UTC().Format(time.RFC3339Nano),
	}

	envelopeJSON, err := json.Marshal(envelope)
	if err != nil {
		return fmt.Errorf("failed to marshal envelope: %w", err)
	}

	// Publish message asynchronously
	// Publish() returns immediately with a PublishResult future
	result := g.topic.Publish(g.ctx, &pubsub.Message{
		Data: envelopeJSON,
	})

	// Send result to background processor (non-blocking if channel has space)
	select {
	case g.pendingResults <- result:
		// Successfully queued
		return nil
	case <-g.ctx.Done():
		// Context cancelled
		return g.ctx.Err()
	}
}

// Stats returns current publishing statistics
func (g *GleanEventsPublisher) Stats() Stats {
	return Stats{
		Published: g.publishedCount.Load(),
		Errors:    g.errorCount.Load(),
	}
}

// Flush waits for all pending publish operations to complete
// Call this before shutdown to ensure no messages are lost
func (g *GleanEventsPublisher) Flush() {
	log.Println("Flushing pending publishes...")

	// Stop accepting new messages and flush pending batches
	g.topic.Stop()

	// Close results channel to signal background processor to finish
	g.once.Do(func() {
		close(g.pendingResults)
	})

	// Wait for background processor to finish
	g.wg.Wait()

	stats := g.Stats()
	log.Printf("Flush complete. Published: %d, Errors: %d", stats.Published, stats.Errors)
}

// Close performs graceful shutdown, flushing all pending messages
func (g *GleanEventsPublisher) Close() error {
	g.Flush()
	return nil
}
