package glean

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// AUTOGENERATED BY glean_parser v19.2.0. DO NOT EDIT.

// required imports
import (
    "bytes"
    "compress/gzip"
    "encoding/json"
    "fmt"
    "io"
    "sync"
    "time"

    pubsub "cloud.google.com/go/pubsub/v2"
    "github.com/google/uuid"
)

// GleanEventsBuilder constructs Pub/Sub messages carrying Glean pings.
// Builder is stateless beyond its app-identity fields; callers own the
// pubsub.Client, the pubsub.Publisher, batching settings, retries, shutdown sequencing, and any
// publish-result metrics
type GleanEventsBuilder struct {
    AppID             string // Application ID to identify application per Glean standards
    AppDisplayVersion string // Version of application emitting the event
    AppChannel        string // Channel to differentiate logs from prod/beta/staging/devel
}

// gzipPool reuses gzip.Writer instances across calls. gzip.NewWriter()
// allocates ~800 KB internally; pooling + Reset() drops per-message
// allocations to near zero at high publish volumes.
var gzipPool = sync.Pool{
    New: func() interface{} {
        return gzip.NewWriter(io.Discard)
    },
}

// compressPayload gzips data using the package-level writer pool. The
// returned slice is caller-owned; only the *gzip.Writer is returned to the
// pool.
func compressPayload(data []byte) ([]byte, error) {
    var buf bytes.Buffer
    // Optimistic preallocation: gzip on small JSON typically achieves ~2x ratio.
    buf.Grow(len(data) / 2)

    gz := gzipPool.Get().(*gzip.Writer)
    gz.Reset(&buf)

    if _, err := gz.Write(data); err != nil {
        gzipPool.Put(gz)
        return nil, fmt.Errorf("gzip write failed: %w", err)
    }
    if err := gz.Close(); err != nil {
        gzipPool.Put(gz)
        return nil, fmt.Errorf("gzip close failed: %w", err)
    }
    gzipPool.Put(gz)
    return buf.Bytes(), nil
}

// exported type for public method parameters
type RequestInfo struct {
    UserAgent string
    IpAddress string
}

// default empty values will be omitted in json from ping struct definition
var defaultRequestInfo = RequestInfo{
    UserAgent: "",
    IpAddress: "",
}

// structs to construct the glean ping
type clientInfo struct {
    TelemetrySDKBuild string `json:"telemetry_sdk_build"`
    FirstRunDate      string `json:"first_run_date"`
    OS                string `json:"os"`
    OSVersion         string `json:"os_version"`
    Architecture      string `json:"architecture"`
    AppBuild          string `json:"app_build"`
    AppDisplayVersion string `json:"app_display_version"`
    AppChannel        string `json:"app_channel"`
}

type pingInfo struct {
    Seq       int    `json:"seq"`
    StartTime string `json:"start_time"`
    EndTime   string `json:"end_time"`
}


type metrics map[string]map[string]any

type pingPayload struct {
    ClientInfo clientInfo   `json:"client_info"`
    PingInfo   pingInfo     `json:"ping_info"`
    Metrics    metrics      `json:"metrics"`
    Events     []gleanEvent `json:"events"`
}

type gleanEvent struct {
    Category  string            `json:"category"`
    Name      string            `json:"name"`
    Timestamp int64             `json:"timestamp"`
    Extra     map[string]string `json:"extra"`
}


func (g GleanEventsBuilder) createClientInfo() clientInfo {
    // Fields with default values are required in the Glean schema, but not used in server context
    return clientInfo{
        TelemetrySDKBuild: "glean_parser v19.2.0",
        FirstRunDate:      "Unknown",
        OS:                "Unknown",
        OSVersion:         "Unknown",
        Architecture:      "Unknown",
        AppBuild:          "Unknown",
        AppDisplayVersion: g.AppDisplayVersion,
        AppChannel:        g.AppChannel,
    }
}

func createPingInfo() pingInfo {
    now := time.Now().UTC().Format("2006-01-02T15:04:05.000Z")
    return pingInfo{
        Seq:       0,
        StartTime: now,
        EndTime:   now,
    }
}


func newGleanEvent(category, name string, extra map[string]string) gleanEvent {
    return gleanEvent{
        Category:  category,
        Name:      name,
        Timestamp: 0,
        Extra: extra,
    }
}

type BackendObjectUpdateEvent struct {
    ObjectType string // A simple name to describe the object whose state changed. For example, `api_request`.
    ObjectState string // A JSON representation of the latest state of the object.
    Linking bool // Indicates the initial linking of the Mozilla account and the third-party account.
}

func (e BackendObjectUpdateEvent) gleanEvent() gleanEvent {
    return newGleanEvent(
        "backend",
        "object_update",
        map[string]string{
            "object_type": e.ObjectType,
            "object_state": e.ObjectState,
            "linking": fmt.Sprintf("%t", e.Linking),
        },
    )
}

type EventsPingEvent interface {
    isEventsPingEvent()
    gleanEvent() gleanEvent
}

func (e BackendObjectUpdateEvent) isEventsPingEvent() {}

type EventsPing struct {
    IdentifiersFxaAccountId string // The user's FxA account ID, if available.
    Event EventsPingEvent // valid event for this ping
}

// BuildEventsPingMessage constructs a Pub/Sub message carrying
// the given `events` ping. The caller publishes the returned message
// (e.g., topic.Publish(ctx, msg)) and owns batching, retries, shutdown
// sequencing, and any publish-result metrics.
//
// Wire-format contract: see
// docs/architecture/decoder_service_specification.md in mozilla/gcp-ingestion.
func (g GleanEventsBuilder) BuildEventsPingMessage(
    requestInfo RequestInfo,
    params EventsPing,
) (*pubsub.Message, error) {
    metrics := metrics{
        "string": {
            "identifiers.fxa_account_id": params.IdentifiersFxaAccountId,
        },
    }

    events := []gleanEvent{}
    if params.Event != nil {
        events = append(events, params.Event.gleanEvent())
    }

    payload := pingPayload{
        ClientInfo: g.createClientInfo(),
        PingInfo:   createPingInfo(),
        Metrics:    metrics,
        Events:     events,
    }

    payloadJSON, err := json.Marshal(payload)
    if err != nil {
        return nil, fmt.Errorf("marshal ping payload: %w", err)
    }
    compressed, err := compressPayload(payloadJSON)
    if err != nil {
        return nil, fmt.Errorf("compress payload: %w", err)
    }

    documentID, err := uuid.NewRandom()
    if err != nil {
        return nil, fmt.Errorf("generate document_id: %w", err)
    }

    attributes := map[string]string{
        "document_namespace": g.AppID,
        "document_type":      "events",
        "document_version":   "1",
        "document_id":        documentID.String(),
    }
    // Skip empty optional attributes; the decoder treats missing and empty
    // the same, and Pub/Sub charges for attribute bytes. The publisher does
    // not set submission_timestamp; the decoder stamps it from publishTime.
    if requestInfo.UserAgent != "" {
        attributes["user_agent"] = requestInfo.UserAgent
    }
    if requestInfo.IpAddress != "" {
        attributes["x_forwarded_for"] = requestInfo.IpAddress
    }

    return &pubsub.Message{
        Data:       compressed,
        Attributes: attributes,
    }, nil
}

// BuildEventsPingMessageWithoutUserInfo constructs a Pub/Sub
// message carrying the given `events` ping with no request-derived
// attributes.
func (g GleanEventsBuilder) BuildEventsPingMessageWithoutUserInfo(
    params EventsPing,
) (*pubsub.Message, error) {
    return g.BuildEventsPingMessage(defaultRequestInfo, params)
}
