package glean

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// AUTOGENERATED BY glean_parser v18.0.6.post1.dev1+g26556941f. DO NOT EDIT.

// required imports
import (
    "context"
    "encoding/json"
    "fmt"
    "log"
    "sync"
    "time"

    "cloud.google.com/go/pubsub"
    "github.com/google/uuid"
    "github.com/prometheus/client_golang/prometheus"
    "github.com/prometheus/client_golang/prometheus/promauto"
)

// Prometheus metrics for monitoring publishing to Pub/Sub
var (
    gleanPublishTotal = promauto.NewCounterVec(
        prometheus.CounterOpts{
            Name: "glean_pubsub_publish_total",
            Help: "Total number of Glean events published to Pub/Sub by status (success/error)",
        },
        []string{"app_id", "document_type", "status"},
    )
)

// publishRequest tracks metadata for async publish operations
type publishRequest struct {
    result       *pubsub.PublishResult
    documentType string
}

// GleanEventsPublisher publishes Glean events directly to Pub/Sub
type GleanEventsPublisher struct {
    AppID             string // Application ID to identify application per Glean standards
    AppDisplayVersion string // Version of application emitting the event
    AppChannel        string // Channel to differentiate logs from prod/beta/staging/devel

    topic          *pubsub.Topic
    ctx            context.Context
    pendingResults chan *publishRequest
    wg             sync.WaitGroup
    once           sync.Once
}

// exported type for public method parameters
type RequestInfo struct {
    UserAgent string
    IpAddress string
}

// default empty values will be omitted in json from ping struct definition
var defaultRequestInfo = RequestInfo{
    UserAgent: "",
    IpAddress: "",
}

// structs to construct the glean ping
type clientInfo struct {
    TelemetrySDKBuild string `json:"telemetry_sdk_build"`
    FirstRunDate      string `json:"first_run_date"`
    OS                string `json:"os"`
    OSVersion         string `json:"os_version"`
    Architecture      string `json:"architecture"`
    AppBuild          string `json:"app_build"`
    AppDisplayVersion string `json:"app_display_version"`
    AppChannel        string `json:"app_channel"`
}

type pingInfo struct {
    Seq       int    `json:"seq"`
    StartTime string `json:"start_time"`
    EndTime   string `json:"end_time"`
}

type ping struct {
    DocumentNamespace string `json:"document_namespace"`
    DocumentType      string `json:"document_type"`
    DocumentVersion   string `json:"document_version"`
    DocumentID        string `json:"document_id"`
    UserAgent         string `json:"user_agent,omitempty"`
    IpAddress         string `json:"ip_address,omitempty"`
    Payload           string `json:"payload"`
}

type metrics map[string]map[string]interface{}

type pingPayload struct {
    ClientInfo clientInfo   `json:"client_info"`
    PingInfo   pingInfo     `json:"ping_info"`
    Metrics    metrics      `json:"metrics"`
    Events     []gleanEvent `json:"events"`
}

type gleanEvent struct {
    Category  string            `json:"category"`
    Name      string            `json:"name"`
    Timestamp int64             `json:"timestamp"`
    Extra     map[string]string `json:"extra"`
}


func (g *GleanEventsPublisher) createClientInfo() clientInfo {
    // Fields with default values are required in the Glean schema, but not used in server context
    return clientInfo{
        TelemetrySDKBuild: "glean_parser v18.0.6.post1.dev1+g26556941f",
        FirstRunDate:      "Unknown",
        OS:                "Unknown",
        OSVersion:         "Unknown",
        Architecture:      "Unknown",
        AppBuild:          "Unknown",
        AppDisplayVersion: g.AppDisplayVersion,
        AppChannel:        g.AppChannel,
    }
}

func createPingInfo() pingInfo {
    now := time.Now().UTC().Format("2006-01-02T15:04:05.000Z")
    return pingInfo{
        Seq:       0,
        StartTime: now,
        EndTime:   now,
    }
}

func (g *GleanEventsPublisher) createPing(documentType string, config RequestInfo, payload pingPayload) (ping, error) {
    payloadJson, err := json.Marshal(payload)
    if err != nil {
        return ping{}, err
    }

    documentID, err := uuid.NewRandom()
    if err != nil {
        return ping{}, err
    }

    return ping{
        DocumentNamespace: g.AppID,
        DocumentType:      documentType,
        DocumentVersion:   "1",
        DocumentID:        documentID.String(),
        UserAgent:         config.UserAgent,
        IpAddress:         config.IpAddress,
        Payload:           string(payloadJson),
    }, nil
}

// NewGleanEventsPublisher creates a new Pub/Sub-based Glean events publisher
// Authentication uses Application Default Credentials (ADC) - typically GKE Workload Identity
func NewGleanEventsPublisher(ctx context.Context, projectID, topicID, appID, appDisplayVersion, appChannel string) (*GleanEventsPublisher, error) {
    client, err := pubsub.NewClient(ctx, projectID)
    if err != nil {
        return nil, fmt.Errorf("failed to create pubsub client: %w", err)
    }

    topic := client.Topic(topicID)

    topic.PublishSettings = pubsub.PublishSettings{
        CountThreshold: 1000,
        ByteThreshold:  10e6,
        DelayThreshold: 10 * time.Millisecond,

        // Flow control prevents memory exhaustion when producing faster than publishing
        FlowControlSettings: pubsub.FlowControlSettings{
            MaxOutstandingMessages: 100000,
            MaxOutstandingBytes:    200e6,
            LimitExceededBehavior:  pubsub.FlowControlBlock,
        },
    }

    publisher := &GleanEventsPublisher{
        AppID:             appID,
        AppDisplayVersion: appDisplayVersion,
        AppChannel:        appChannel,
        topic:             topic,
        ctx:               ctx,
        pendingResults:    make(chan *publishRequest, 10000),
    }

    // Start background goroutine to process publish results asynchronously
    publisher.wg.Add(1)
    go publisher.processResults()

    return publisher, nil
}

// processResults runs in background to handle publish results asynchronously
func (g *GleanEventsPublisher) processResults() {
    defer g.wg.Done()

    for req := range g.pendingResults {
        _, err := req.result.Get(g.ctx)

        status := "success"
        if err != nil {
            status = "error"
            log.Printf("Pub/Sub publish error: %v", err)
        }

        gleanPublishTotal.WithLabelValues(
            g.AppID,
            req.documentType,
            status,
        ).Inc()
    }
}

// construct the Glean envelope and publish to Pub/Sub asynchronously
func (g *GleanEventsPublisher) publish(
    documentType string,
    requestInfo RequestInfo,
    metrics metrics,
    events []gleanEvent,
) error {
    var telemetryPayload = pingPayload{
        ClientInfo: g.createClientInfo(),
        PingInfo:   createPingInfo(),
        Metrics:    metrics,
        Events:     events,
    }

    ping, err := g.createPing(documentType, requestInfo, telemetryPayload)
    if err != nil {
        return fmt.Errorf("failed to create ping: %w", err)
    }

    var envelope = ping

    envelopeJSON, err := json.Marshal(envelope)
    if err != nil {
        return fmt.Errorf("failed to marshal envelope: %w", err)
    }

    // Publish message asynchronously
    // Publish() returns immediately with a PublishResult future
    result := g.topic.Publish(g.ctx, &pubsub.Message{
        Data: envelopeJSON,
    })

    // Create publish request with metadata for metrics tracking
    req := &publishRequest{
        result:       result,
        documentType: documentType,
    }

    // Send request to background processor (non-blocking if channel has space)
    select {
    case g.pendingResults <- req:
        // Successfully queued
        return nil
    case <-g.ctx.Done():
        // Context cancelled
        return g.ctx.Err()
    }
}

// Flush waits for all pending publish operations to complete
// Call this before shutdown to ensure no messages are lost
func (g *GleanEventsPublisher) Flush() {
    log.Println("Flushing pending publishes...")

    // Stop accepting new messages and flush pending batches
    g.topic.Stop()

    // Close results channel to signal background processor to finish
    g.once.Do(func() {
        close(g.pendingResults)
    })

    // Wait for background processor to finish
    g.wg.Wait()
	log.Println("All pending publishes flushed.")
}

// Close performs graceful shutdown, flushing all pending messages
func (g *GleanEventsPublisher) Close() error {
    g.Flush()
    return nil
}

func newGleanEvent(category, name string, extra map[string]string) gleanEvent {
    return gleanEvent{
        Category:  category,
        Name:      name,
        Timestamp: time.Now().UnixMilli(),
        Extra: extra,
    }
}

type BackendObjectUpdateEvent struct {
    ObjectType string // A simple name to describe the object whose state changed. For example, `api_request`.
    ObjectState string // A JSON representation of the latest state of the object.
    Linking bool // Indicates the initial linking of the Mozilla account and the third-party account.
}

func (e BackendObjectUpdateEvent) gleanEvent() gleanEvent {
    return newGleanEvent(
        "backend",
        "object_update",
        map[string]string{
            "object_type": e.ObjectType,
            "object_state": e.ObjectState,
            "linking": fmt.Sprintf("%t", e.Linking),
        },
    )
}

type EventsPingEvent interface {
    isEventsPingEvent()
    gleanEvent() gleanEvent
}

func (e BackendObjectUpdateEvent) isEventsPingEvent() {}

type EventsPing struct {
    IdentifiersFxaAccountId string // The user's FxA account ID, if available.
    Event EventsPingEvent // valid event for this ping
}

// Record and submit `events` ping
func (g *GleanEventsPublisher) RecordEventsPing(
    requestInfo RequestInfo,
    params EventsPing,
) error {
    metrics := metrics{
        "string": {
            "identifiers.fxa_account_id": params.IdentifiersFxaAccountId,
        },
    }

    events := []gleanEvent{}
    if params.Event != nil {
        events = append(events, params.Event.gleanEvent())
    }
    return g.publish("events", requestInfo, metrics, events)
}

// Record and submit `events` ping omitting user request info
func (g *GleanEventsPublisher) RecordEventsPingWithoutUserInfo(
    params EventsPing,
) error {
    return g.RecordEventsPing(defaultRequestInfo, params)
}
