package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"sync/atomic"
	"syscall"
	"test-go-publisher/glean"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

// Instrumentation counters to identify bottlenecks
var (
	generatedCount    atomic.Int64 // Total events generated
	publishCallCount  atomic.Int64 // Number of Publish() calls made
	publishBlockCount atomic.Int64 // Number of times Publish() blocked (>1ms)
)

// logPrometheusMetrics queries and logs Glean Prometheus metrics for testing/debugging
func logPrometheusMetrics() {
	metricFamilies, err := prometheus.DefaultGatherer.Gather()
	if err != nil {
		log.Printf("Error gathering metrics: %v", err)
		return
	}

	var totalSuccess, totalError int64

	for _, mf := range metricFamilies {
		// Only process glean_pubsub_publish_total metric
		if mf.GetName() != "glean_pubsub_publish_total" {
			continue
		}

		for _, m := range mf.GetMetric() {
			labels := make(map[string]string)
			for _, l := range m.GetLabel() {
				labels[l.GetName()] = l.GetValue()
			}
			val := int64(m.GetCounter().GetValue())
			if labels["status"] == "success" {
				totalSuccess += val
			} else if labels["status"] == "error" {
				totalError += val
			}
		}
	}

	log.Printf("Prometheus Metrics: Published=%d, Errors=%d", totalSuccess, totalError)
}

func main() {
	// Command-line flags
	projectID := flag.String("project", getEnv("PROJECT_ID", ""), "GCP project ID (required)")
	topicID := flag.String("topic", getEnv("TOPIC_ID", ""), "Pub/Sub topic name (required)")
	eventsPerSec := flag.Int("rate", getEnvInt("EVENTS_PER_SEC", 1), "Events per second to generate")
	duration := flag.Duration("duration", 0, "Run duration (0 = infinite)")
	flag.Parse()

	if *projectID == "" {
		log.Fatal("--project or PROJECT_ID environment variable is required")
	}

	if *topicID == "" {
		log.Fatal("--topic or TOPIC_ID environment variable is required")
	}

	log.Printf("Starting Glean Pub/Sub publisher")
	log.Printf("Configuration: project=%s, topic=%s, rate=%d events/sec, duration=%v",
		*projectID, *topicID, *eventsPerSec, *duration)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// This uses code generated by [glean_parser](https://github.com/mozilla/glean_parser)
	// To generate the code under `glean/server_events.go`, check out the go_direct_pubsub branch of glean_parser (https://github.com/mozilla/glean_parser/pull/821) and run:
	// glean_parser translate tests/data/server_metrics_with_event.yaml -f go_server_pubsub -o ../server-telemetry-node-poc/test-go-publisher/glean

	// ============================================================================
	// PRODUCTION CODE: Initialize Glean Publisher
	// ============================================================================
	// Copy this block to your application initialization code (e.g., main() or init())
	publisher, err := glean.NewGleanEventsPublisher(
		ctx,
		*projectID,
		*topicID,
		"accounts_backend", // Your application ID
		"0.0.1",            // Your application version
		"nightly",          // Your deployment channel (prod/stage/dev)
	)
	if err != nil {
		log.Fatalf("Failed to create Pub/Sub publisher: %v", err)
	}
	defer publisher.Close()
	// ============================================================================

	// TEST HARNESS: Track overall start time for rate calculation
	overallStartTime := time.Now()

	// TEST HARNESS: Stats reporting (not needed in production - use Prometheus /metrics endpoint)
	go func() {
		ticker := time.NewTicker(10 * time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				generated := generatedCount.Load()
				publishCalls := publishCallCount.Load()
				blocked := publishBlockCount.Load()
				elapsed := time.Since(overallStartTime).Seconds()

				actualRate := float64(generated) / elapsed
				blockedPct := 0.0
				if publishCalls > 0 {
					blockedPct = float64(blocked) / float64(publishCalls) * 100
				}

				log.Printf("Stats: Generated=%d (%.0f/s), PublishCalls=%d, Blocked=%d (%.1f%%)",
					generated, actualRate, publishCalls, blocked, blockedPct)
				logPrometheusMetrics()
			case <-ctx.Done():
				return
			}
		}
	}()

	// ============================================================================
	// PRODUCTION CODE: Graceful Handler Shutdown
	// ============================================================================
	// Copy this block to ensure no messages are lost on application shutdown
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigChan
		log.Println("Received shutdown signal, flushing pending messages...")
		publisher.Flush()
		os.Exit(0)
	}()
	// ============================================================================

	// TEST HARNESS: Event generation loop (replace with your application logic)
	ticker := time.NewTicker(10 * time.Millisecond)
	defer ticker.Stop()

	startTime := time.Now()
	eventCount := 0

	for {
		select {
		case <-ticker.C:
			// Calculate how many events we SHOULD have generated by now based on elapsed time
			elapsed := time.Since(startTime).Seconds()
			expectedCount := int(elapsed * float64(*eventsPerSec))

			// Generate all events we're "behind" on (burst generation)
			for eventCount < expectedCount {
				// TEST HARNESS: Track event generation
				generatedCount.Add(1)
				publishStart := time.Now()

				// ================================================================
				// PRODUCTION CODE: Record Glean Event
				// ================================================================
				// Copy this pattern wherever you need to submit telemetry events
				requestInfo := glean.RequestInfo{}
				params := glean.EventsPing{
					IdentifiersFxaAccountId: fmt.Sprintf("account_%d", eventCount),
					Event: glean.BackendObjectUpdateEvent{
						ObjectType:  "api_request",
						ObjectState: fmt.Sprintf(`{"request_id": %d, "timestamp": "%s"}`, eventCount, time.Now().Format(time.RFC3339)),
						Linking:     eventCount%2 == 0,
					},
				}

				if err := publisher.RecordEventsPing(requestInfo, params); err != nil {
					log.Printf("Error recording event: %v", err)
				}
				// ================================================================

				// TEST HARNESS: Track instrumentation
				publishCallCount.Add(1)
				publishDuration := time.Since(publishStart)
				if publishDuration > 1*time.Millisecond {
					publishBlockCount.Add(1)
				}

				eventCount++
			}

			if *duration > 0 && time.Since(startTime) >= *duration {
				elapsed := time.Since(startTime).Seconds()
				generated := generatedCount.Load()
				publishCalls := publishCallCount.Load()
				blocked := publishBlockCount.Load()

				blockedPct := 0.0
				if publishCalls > 0 {
					blockedPct = float64(blocked) / float64(publishCalls) * 100
				}

				log.Printf("=== FINAL STATS ===")
				log.Printf("Duration: %.2fs", elapsed)
				log.Printf("Target rate: %d msgs/s", *eventsPerSec)
				log.Printf("Generated: %d events (expected: %d, actual rate: %.0f/s)",
					generated, int(elapsed*float64(*eventsPerSec)), float64(generated)/elapsed)
				log.Printf("PublishCalls: %d", publishCalls)
				log.Printf("Blocked: %d times (%.1f%% of calls took >1ms)", blocked, blockedPct)
				logPrometheusMetrics()
				log.Printf("==================")
				log.Printf("Note: Production applications should expose metrics via HTTP:")
				log.Printf("  http.Handle(\"/metrics\", promhttp.Handler())")

				publisher.Flush()
				return
			}

		case <-ctx.Done():
			log.Printf("Context cancelled, generated %d events", eventCount)
			return
		}
	}
}

// getEnv returns environment variable value or default
func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

// getEnvInt returns environment variable as int or default
func getEnvInt(key string, defaultValue int) int {
	if value := os.Getenv(key); value != "" {
		var intValue int
		if _, err := fmt.Sscanf(value, "%d", &intValue); err == nil {
			return intValue
		}
	}
	return defaultValue
}
