package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"sync/atomic"
	"syscall"
	"test-go-publisher/glean"
	"time"
)

// Instrumentation counters to identify bottlenecks
var (
	generatedCount    atomic.Int64 // Total events generated
	publishCallCount  atomic.Int64 // Number of Publish() calls made
	publishBlockCount atomic.Int64 // Number of times Publish() blocked (>1ms)
)

func main() {
	// Command-line flags
	projectID := flag.String("project", getEnv("PROJECT_ID", ""), "GCP project ID (required)")
	topicID := flag.String("topic", getEnv("TOPIC_ID", ""), "Pub/Sub topic name (required)")
	eventsPerSec := flag.Int("rate", getEnvInt("EVENTS_PER_SEC", 1), "Events per second to generate")
	duration := flag.Duration("duration", 0, "Run duration (0 = infinite)")
	flag.Parse()

	if *projectID == "" {
		log.Fatal("--project or PROJECT_ID environment variable is required")
	}

	if *topicID == "" {
		log.Fatal("--topic or TOPIC_ID environment variable is required")
	}

	log.Printf("Starting Glean Pub/Sub publisher")
	log.Printf("Configuration: project=%s, topic=%s, rate=%d events/sec, duration=%v",
		*projectID, *topicID, *eventsPerSec, *duration)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Create publisher
	publisher, err := glean.NewGleanEventsPublisher(
		ctx,
		*projectID,
		*topicID,
		"accounts_backend",
		"0.0.1",
		"nightly",
	)
	if err != nil {
		log.Fatalf("Failed to create Pub/Sub publisher: %v", err)
	}
	defer publisher.Close()

	// Track overall start time for rate calculation
	overallStartTime := time.Now()

	// Start stats reporting with detailed instrumentation
	go func() {
		ticker := time.NewTicker(10 * time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				stats := publisher.Stats()
				generated := generatedCount.Load()
				publishCalls := publishCallCount.Load()
				blocked := publishBlockCount.Load()
				elapsed := time.Since(overallStartTime).Seconds()

				actualRate := float64(generated) / elapsed
				publishRate := float64(stats.Published) / elapsed

				log.Printf("Stats: Generated=%d (%.0f/s), PublishCalls=%d, Blocked=%d (%.1f%%), Published=%d (%.0f/s), Errors=%d",
					generated, actualRate, publishCalls, blocked,
					float64(blocked)/float64(publishCalls)*100,
					stats.Published, publishRate, stats.Errors)
			case <-ctx.Done():
				return
			}
		}
	}()

	// Graceful shutdown
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigChan
		log.Println("Received shutdown signal, flushing pending messages...")
		publisher.Flush()
		os.Exit(0)
	}()

	ticker := time.NewTicker(10 * time.Millisecond)
	defer ticker.Stop()

	startTime := time.Now()
	eventCount := 0

	for {
		select {
		case <-ticker.C:
			// Calculate how many events we SHOULD have generated by now based on elapsed time
			elapsed := time.Since(startTime).Seconds()
			expectedCount := int(elapsed * float64(*eventsPerSec))

			// Generate all events we're "behind" on (burst generation)
			for eventCount < expectedCount {
				// Track event generation
				generatedCount.Add(1)

				// Track publish call timing to detect flow control blocking
				publishStart := time.Now()

				requestInfo := glean.RequestInfo{}
				params := glean.EventsPing{
					IdentifiersFxaAccountId: fmt.Sprintf("account_%d", eventCount),
					Event: glean.BackendObjectUpdateEvent{
						ObjectType:  "api_request",
						ObjectState: fmt.Sprintf(`{"request_id": %d, "timestamp": "%s"}`, eventCount, time.Now().Format(time.RFC3339)),
						Linking:     eventCount%2 == 0,
					},
				}

				publishCallCount.Add(1)
				if err := publisher.RecordEventsPing(requestInfo, params); err != nil {
					log.Printf("Error recording event: %v", err)
				}

				// Detect if Publish() blocked due to flow control
				publishDuration := time.Since(publishStart)
				if publishDuration > 1*time.Millisecond {
					publishBlockCount.Add(1)
				}

				eventCount++
			}

			if *duration > 0 && time.Since(startTime) >= *duration {
				elapsed := time.Since(startTime).Seconds()
				generated := generatedCount.Load()
				publishCalls := publishCallCount.Load()
				blocked := publishBlockCount.Load()
				stats := publisher.Stats()

				log.Printf("=== FINAL STATS ===")
				log.Printf("Duration: %.2fs", elapsed)
				log.Printf("Target rate: %d msgs/s", *eventsPerSec)
				log.Printf("Generated: %d events (expected: %d, actual rate: %.0f/s)",
					generated, int(elapsed*float64(*eventsPerSec)), float64(generated)/elapsed)
				log.Printf("PublishCalls: %d", publishCalls)
				log.Printf("Blocked: %d times (%.1f%% of calls took >1ms)",
					blocked, float64(blocked)/float64(publishCalls)*100)
				log.Printf("Published: %d (%.0f/s)", stats.Published, float64(stats.Published)/elapsed)
				log.Printf("Errors: %d", stats.Errors)
				log.Printf("==================")

				publisher.Flush()
				return
			}

		case <-ctx.Done():
			log.Printf("Context cancelled, generated %d events", eventCount)
			return
		}
	}
}

// getEnv returns environment variable value or default
func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

// getEnvInt returns environment variable as int or default
func getEnvInt(key string, defaultValue int) int {
	if value := os.Getenv(key); value != "" {
		var intValue int
		if _, err := fmt.Sscanf(value, "%d", &intValue); err == nil {
			return intValue
		}
	}
	return defaultValue
}
