package main

import (
	"fmt"
	"test-go-logger/glean"
	"time"
)

func main() {
	fmt.Println("Starting logger loop")

	// This uses code generated by [glean_parser](https://github.com/mozilla/glean_parser)
	// To generate the code under `glean/server_events.go`, check out the main branch of glean_parser and run:
	// glean_parser translate tests/data/server_metrics_with_event.yaml -f go_server -o ../server-telemetry-node-poc/test-go-logger/glean

	for {
		logger := glean.GleanEventsLogger{
			AppID:             "accounts_backend",
			AppDisplayVersion: "0.0.1",
			AppChannel:        "nightly",
		}

		requestInfo := glean.RequestInfo{}

		params := glean.EventsPing{
			IdentifiersFxaAccountId: "your_account_id",
			Event: glean.BackendObjectUpdateEvent{
				ObjectType: "your_object_type",
				ObjectState: "your_object_state",
				Linking: true,
			},
		}

		logger.RecordEventsPing(requestInfo, params)

		// incorrect output, Decoder will send it to error stream
		fmt.Println("{\"Type\":\"glean-server-event\",\"Fields\":{}}")

		time.Sleep(time.Second)
	}
}
