apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-js-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      component: test-js-logger
  template:
    metadata:
      labels:
        component: test-js-logger
    spec:
      containers:
        - name: test-js-logger
          image: gcr.io/akomar-server-telemetry-poc/test-js-logger
