apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-js-logger
spec:
  replicas: 3
  selector:
    matchLabels:
      component: test-js-logger
  template:
    metadata:
      labels:
        component: test-js-logger
    spec:
      containers:
        - name: test-js-logger
          image: gcr.io/${project_id}/test-js-logger
